#!/bin/bash

mvn clean compile assembly:single   

if (( $? == 0 )); then

	echo -e "Starting client on default ports!\n"
	java -jar target/TexasHoldem-0.0.1-SNAPSHOT-jar-with-dependencies.jar -c

fi
